/****************************************************************************
**
** Copyright (C) 2014
**
** This file is generated by the Magus toolkit
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
** "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
** LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
** A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
** OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
** LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
** DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
** THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
** (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
** OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE."
**
****************************************************************************/

// Include
#include <QVBoxLayout>
#include <QMessageBox>
#include <QDir>
#include <QLabel>
#include <QByteArray>
#include <QImageReader>
#include "asset_texture_dialog.h"

namespace Magus
{
    //****************************************************************************/
    QtTextureDialog::QtTextureDialog(QWidget* parent) : QDialog(parent)
    {
        setWindowTitle(QString("Texture selection"));
        mFileNameTexture = QString("");
        mBaseFileNameTexture = QString("");
        mTextureSize = QSize(128, 128);
        QHBoxLayout* mainLayout = new QHBoxLayout;
        QVBoxLayout* textureSelectionLayout = new QVBoxLayout;

        mButtonBox = new QDialogButtonBox(QDialogButtonBox::Ok | QDialogButtonBox::Cancel, this);
        connect(mButtonBox, SIGNAL(accepted()), this, SLOT(accept()));
        connect(mButtonBox, SIGNAL(rejected()), this, SLOT(reject()));

        // Define selection widget (QListView)
        mSelectionList = new QListView(this);
        mSelectionList->setViewMode(QListView::IconMode);
        mSelectionList->setIconSize(mTextureSize);
        mSelectionList->setSpacing(2);
        mSelectionList->setMovement(QListView::Snap);
        mSelectionList->setFlow(QListView::LeftToRight);
        mSelectionList->setWrapping(true);
        mSelectionList->setDragEnabled(false);
        mSelectionList->setAcceptDrops(false);
        mSelectionList->setDropIndicatorShown(false);
        mSelectionList->setMinimumSize(QSize(840, 640));
        mSelectionModel = new QtTextureDialogModel();
        mSelectionList->setModel(mSelectionModel);
        connect(mSelectionList, SIGNAL(doubleClicked(QModelIndex)), this, SLOT(doubleClicked(void)));

        // Define a directory tree. If a directory is selected and the button is pressed, signal 'directorySelected' is emitted
        mDirTree = new QtDirTree(this);
        mDirTree->setButtonTitle(QString("Display textures"));
        connect(mDirTree, SIGNAL(directorySelected(const QString&)), this, SLOT(directorySelected(const QString&)));

        // Layout
        textureSelectionLayout->addWidget(mSelectionList);
        textureSelectionLayout->addWidget(mButtonBox);
        mainLayout->addWidget(mDirTree, 1);
        mainLayout->addLayout(textureSelectionLayout, 3);
        setLayout(mainLayout);
    }

    //****************************************************************************/
    void QtTextureDialog::fillTextures(const QString& searchPath)
    {
        setCursor(Qt::WaitCursor);
        // Get all texture files from all dirs/subdirs
        QDir dir(searchPath);
        dir.makeAbsolute();

        if (dir.exists())
        {
            //mSelectionModel->clear();
            Q_FOREACH(QFileInfo info, dir.entryInfoList(QDir::NoDotAndDotDot | QDir::System | QDir::Hidden  | QDir::AllDirs | QDir::Files, QDir::DirsFirst))
            {
                if (info.isDir())
                {
                    fillTextures(info.absoluteFilePath());
                }
                else
                {
                    QString fileName = info.absoluteFilePath();
                    QByteArray imageFormat = QImageReader::imageFormat(fileName);
                    if (!imageFormat.isEmpty())
                    {
                        // It is an image Qt is able to display
                        mSelectionModel->addTexture(info.absoluteFilePath(), mTextureSize);
                    }
                }
            }
        }
        setCursor(Qt::ArrowCursor);
    }

    //****************************************************************************/
    const QString& QtTextureDialog::getTextureFileName(void)
    {
        return mFileNameTexture;
    }

    //****************************************************************************/
    const QString& QtTextureDialog::getTextureBaseFileName(void)
    {
        return mBaseFileNameTexture;
    }

    //****************************************************************************/
    void QtTextureDialog::doubleClicked(void)
    {
        accept();
    }

    //****************************************************************************/
    void QtTextureDialog::accept (void)
    {
        QModelIndex selectedTexture = mSelectionList->currentIndex();
        QString fileNameTexture = mSelectionModel->getName(selectedTexture);
        if (!fileNameTexture.isEmpty())
        {
            mFileNameTexture = fileNameTexture;
        }
        QDialog::accept();
    }

    //****************************************************************************/
    void QtTextureDialog::directorySelected(const QString& path)
    {
        mSelectionModel->clear();
        fillTextures(path);
    }
}
