/****************************************************************************
**
** Copyright (C) 2014
**
** This file is generated by the Magus toolkit
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
** "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
** LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
** A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
** OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
** LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
** DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
** THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
** (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
** OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE."
**
****************************************************************************/

// Include
#include "sme_node_technique.h"
#include "sme_node_porttype.h"
#include "constants.h"

namespace Magus
{
    //****************************************************************************/
    QtNodeTechnique::QtNodeTechnique(QString title, QGraphicsItem* parent) : QtNode(title, parent)
    {
        // Define the connection policy
        QtMaterialInPortType materialInPortType;
        QtTechniqueOutPortType techniqueOutPortType;
        QtTechniqueInPortType techniqueInPortType;
        QtPassOutPortType passOutPortType;
        materialInPortType.addPortTypeToConnectionPolicy(techniqueOutPortType);
        passOutPortType.addPortTypeToConnectionPolicy(techniqueInPortType);

        // Custome node settings
        setTitleColor(Qt::white);
        setHeaderTitleIcon(ICON_TECHNIQUE_BOLD);
        setAction1Icon(ICON_MINMAX);
        setAction2Icon(ICON_CLOSE);
        alignTitle(ALIGNED_LEFT);
        setHeaderColor(QColor("#874E96"));
        createPort(PORT_ID_TECHNIQUE,
                    PORT_MATERIAL_IN, materialInPortType,
                    QColor("#5853BD"),
                    PORT_SHAPE_CIRCLE,
                    ALIGNED_LEFT,
                    QColor("#5853BD"));
        createPort(PORT_ID_TECHNIQUE + 1,
                    PORT_PASS_OUT,
                    passOutPortType,
                    QColor("#5D964E"),
                    PORT_SHAPE_CIRCLE,
                    ALIGNED_RIGHT,
                    QColor("#5D964E"));
        createPort(PORT_ID_TECHNIQUE + 2,
                    PORT_PASS_OUT,
                    passOutPortType,
                    QColor("#5D964E"),
                    PORT_SHAPE_CIRCLE,
                    ALIGNED_RIGHT,
                    QColor("#5D964E"));
        createPort(PORT_ID_TECHNIQUE + 3,
                    PORT_PASS_OUT,
                    passOutPortType,
                    QColor("#5D964E"),
                    PORT_SHAPE_CIRCLE,
                    ALIGNED_RIGHT,
                    QColor("#5D964E"));
        createPort(PORT_ID_TECHNIQUE + 4,
                    PORT_PASS_OUT,
                    passOutPortType,
                    QColor("#5D964E"),
                    PORT_SHAPE_CIRCLE,
                    ALIGNED_RIGHT,
                    QColor("#5D964E"));
        setPortNameColor(Qt::white);
        setZoom(0.9);
    }

    //****************************************************************************/
    QtNodeTechnique::~QtNodeTechnique(void)
    {
    }

}
