/****************************************************************************
**
** Copyright (C) 2016
**
** This file is generated by the Magus toolkit
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
** "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
** LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
** A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
** OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
** LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
** DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
** THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
** (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
** OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE."
**
****************************************************************************/

#ifndef AssetDOCWIDGET_H
#define AssetDOCWIDGET_H

#include <QtWidgets>
#include "constants.h"
#include <QMenu>
#include <QAction>
#include <QToolBar>
#include <QTabWidget>
#include "sme_asset_material.h"
#include "sme_asset_technique.h"
#include "sme_asset_pass.h"
#include "sme_asset_texture_unit.h"

QT_BEGIN_NAMESPACE
class QDockWidget;
QT_END_NAMESPACE

class MainWindow;

/****************************************************************************
 This class represents a DockWidget
 ***************************************************************************/
class AssetDockWidget : public QDockWidget
{
	Q_OBJECT

	public:
        AssetDockWidget(QString title, MainWindow* parent, Qt::WindowFlags flags = 0);
		~AssetDockWidget(void);
		void createActions(void);
		void createMenus(void);
		void createToolBars(void);
        void setAssetMaterialVisible(bool visible);
        void setAssetTechniqueVisible(bool visible);
        void setAssetPassVisible(bool visible);
        void setAssetTextureUnitVisible(bool visible);
        void start(void);
        Magus::QtAssetMaterial* mAssetMaterial;
        Magus::QtAssetTechnique* mAssetTechnique;
        Magus::QtAssetPass* mAssetPass;
        Magus::QtAssetTextureUnit* mAssetTextureUnit;

	private slots:


	private:
		MainWindow* mParent;
        QMainWindow* mInnerMain;
};

#endif

