/****************************************************************************
**
** Copyright (C) 2014
**
** This file is generated by the Magus toolkit
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
** "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
** LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
** A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
** OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
** LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
** DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
** THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
** (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
** OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE."
**
****************************************************************************/

#ifndef MAGUS_ASSET_TEXTURE_DIALOG_H
#define MAGUS_ASSET_TEXTURE_DIALOG_H

#include <QWidget>
#include <QListView>
#include <QDialog>
#include <QTableView>
#include <QDialogButtonBox>
#include "asset_texture_dialog_model.h"
#include "asset_dirtree.h"

QT_BEGIN_NAMESPACE

QT_END_NAMESPACE

namespace Magus
{
    /****************************************************************************
    Selection dialog of texture files
    ****************************************************************************/
    class QtTextureDialog : public QDialog
    {
        Q_OBJECT

        public:
            QtTextureDialog(QWidget* parent = 0);
            virtual ~QtTextureDialog(void){};
            void fillTextures(const QString& searchPath);
            const QString& getTextureFileName(void);
            const QString& getTextureBaseFileName(void);

        public slots:
            void accept (void);

        protected slots:
            void doubleClicked(void);
            void directorySelected(const QString&);

        private:
            QListView *mSelectionList;
            QtTextureDialogModel* mSelectionModel;
            QDialogButtonBox* mButtonBox;
            QSize mTextureSize;
            QString mFileNameTexture; // Fully qualified filename (path + filename)
            QString mBaseFileNameTexture; // Filename without path
            QtDirTree* mDirTree;
    };
}

#endif
