/****************************************************************************
**
** Copyright (C) 2014
**
** This file is generated by the Magus toolkit
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
** "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
** LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
** A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
** OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
** LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
** DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
** THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
** (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
** OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE."
**
****************************************************************************/

#ifndef MAGUS_OGRE_RENDER_MANAGER_H
#define MAGUS_OGRE_RENDER_MANAGER_H

#include <QObject>
#include "ogre_widget.h"

/****************************************************************************
 This class manages the rendering of the Ogre widgets
****************************************************************************/
class OgreManager : public QObject
{
    public:
        OgreManager(void);
        virtual ~OgreManager(void);
        void renderOgreWidgetsOneFrame(void);
        void registerQtOgreWidget(int widgetId, QOgre::Widget* widget);
        void unregisterQtOgreWidget(int widgetId);
        Ogre::Root* getOgreRoot(void) const {return mRoot;};
        QOgre::Widget* getOgreWidget(int widgetId) const;

    private:
        QMap<int, QOgre::Widget*> mQtOgreWidgetMap;
        Ogre::Root* mRoot;
        Ogre::Timer* mTimer;
        Ogre::String mResourcesCfg;
        Ogre::String mPluginsCfg;
};

//****************************************************************************/
#endif
