/****************************************************************************
**
** Copyright (C) 2014
**
** This file is generated by the Magus toolkit
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
** "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
** LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
** A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
** OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
** LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
** DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
** THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
** (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
** OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE."
**
****************************************************************************/

// Include
#include "mainwindow.h"
#include "Asset_dockwidget.h"
#include "constants.h"

//****************************************************************************/
AssetDockWidget::AssetDockWidget(QString title, MainWindow* parent, Qt::WindowFlags flags) : 
	QDockWidget (title, parent, flags), 
	mParent(parent)
{
    // Perform standard functions
    createActions();
    createMenus();
    createToolBars();
    setContentsMargins(0, 0, 0, 0);
    mAssetMaterial = new Magus::QtAssetMaterial(ICON_MATERIAL);
    mAssetTechnique = new Magus::QtAssetTechnique(ICON_TECHNIQUE);
    mAssetPass = new Magus::QtAssetPass(ICON_PASS);
    mAssetTextureUnit = new Magus::QtAssetTextureUnit(ICON_TEXTURE);
}

//****************************************************************************/
AssetDockWidget::~AssetDockWidget(void)
{
}

//****************************************************************************/
void AssetDockWidget::createActions(void)
{

}

//****************************************************************************/
void AssetDockWidget::createMenus(void)
{

}

//****************************************************************************/
void AssetDockWidget::createToolBars(void)
{

}

//****************************************************************************/
void AssetDockWidget::setAssetMaterialVisible(bool visible)
{
    mAssetMaterial->setVisible(visible);
    if (visible)
        setWidget(mAssetMaterial);
}

//****************************************************************************/
void AssetDockWidget::setAssetTechniqueVisible(bool visible)
{
    mAssetTechnique->setVisible(visible);
    if (visible)
        setWidget(mAssetTechnique);
}

//****************************************************************************/
void AssetDockWidget::setAssetPassVisible(bool visible)
{
    mAssetPass->setVisible(visible);
    if (visible)
        setWidget(mAssetPass);
}

//****************************************************************************/
void AssetDockWidget::setAssetTextureUnitVisible(bool visible)
{
    mAssetTextureUnit->setVisible(visible);
    if (visible)
        setWidget(mAssetTextureUnit);
}

//****************************************************************************/
void AssetDockWidget::start(void)
{
    setAssetMaterialVisible(false);
    setAssetTechniqueVisible(false);
    setAssetPassVisible(false);
    setAssetTextureUnitVisible(false);
}
