/****************************************************************************
**
** Copyright (C) 2015
**
** This file is generated by the Magus toolkit
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
** "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
** LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
** A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
** OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
** LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
** DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
** THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
** (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
** OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE."
**
****************************************************************************/

// Include
#include <QHBoxLayout>
#include <QVBoxLayout>
#include <QMessageBox>
#include <QDir>
#include <QLabel>
#include <QImageReader>
#include <QListWidgetItem>
#include <QMouseEvent>
#include "tool_audiowidget.h"

namespace Magus
{
    //****************************************************************************/
    QtAudioAndText::QtAudioAndText(const QString& iconDir,
                                   Source source,
                                   const QString& name,
                                   const QString& baseName,
                                   const QSize& size,
                                   QWidget* parent) : QWidget(parent)
    {
        setContentsMargins(-8, -8, -8, -8);
        setMinimumSize(size);
        setMaximumSize(size);
        QHBoxLayout* mainLayout = new QHBoxLayout;
        QVBoxLayout* textureAndNameLayout = new QVBoxLayout;
        mPixmapAudioPlay = QPixmap(iconDir + TOOL_AUDIOWIDGET_ICON_PLAY);
        mPixmapAudioPause = QPixmap(iconDir + TOOL_AUDIOWIDGET_ICON_PAUSE);
        mPixmapAudioStop = QPixmap(iconDir + TOOL_AUDIOWIDGET_ICON_STOP);

        mName = name;
        mBaseName = baseName;
        mSource = source;
        mBaseNameEdit = new QLineEdit;
        mBaseNameEdit->setText(mBaseName);
        mBaseNameEdit->setEnabled(false);

        mTextureLabel = new QLabel();
        mTextureLabel->setPixmap(mPixmapAudioStop);
        mTextureLabel->setScaledContents(true);

        // Layout
        textureAndNameLayout->addWidget(mTextureLabel, 1000);
        textureAndNameLayout->addWidget(mBaseNameEdit, 1);
        mainLayout->addLayout(textureAndNameLayout);
        setLayout(mainLayout);
    }

    //****************************************************************************/
    QtAudioAndText::~QtAudioAndText(void)
    {
    }

    //****************************************************************************/
    void QtAudioAndText::setPlay(void)
    {
        mTextureLabel->setPixmap(mPixmapAudioPlay);
    }

    //****************************************************************************/
    void QtAudioAndText::setPause(void)
    {
        mTextureLabel->setPixmap(mPixmapAudioPause);
    }

    //****************************************************************************/
    void QtAudioAndText::setStop(void)
    {
        mTextureLabel->setPixmap(mPixmapAudioStop);
    }

    //****************************************************************************/
    //****************************************************************************/
    //****************************************************************************/
    QtAudioWidget::QtAudioWidget(const QString& iconDir, QWidget* parent) : QWidget(parent)
    {
        mLastSelectedTextureAndText = 0;
        mAudioPlayer = new QMediaPlayer();
        connect(mAudioPlayer, SIGNAL(positionChanged(qint64)), this, SLOT(handlePositionChanged(qint64)));
        mContextMenu = 0;
        mIconDir = iconDir;
        setWindowTitle(QString("Texture selection"));
        mNameTexture = QString("");
        mBaseNameTexture = QString("");
        mTextureSize = QSize(128, 128);
        QHBoxLayout* mainLayout = new QHBoxLayout;
        QVBoxLayout* textureSelectionLayout = new QVBoxLayout;

        // Define selection widget (QListWidget)
        mSelectionList = new QListWidget();
        mSelectionList->setViewMode(QListView::ListMode);
        mSelectionList->setWrapping(true);
        mSelectionList->setWordWrap(true);
        mSelectionList->setSpacing(0);
        mSelectionList->setUniformItemSizes(true);
        mSelectionList->setMovement(QListView::Snap);
        mSelectionList->setFlow(QListView::LeftToRight);
        mSelectionList->setAcceptDrops(false);
        mSelectionList->setDropIndicatorShown(false);
        mSelectionList->setMouseTracking(true);

        // Layout
        textureSelectionLayout->addWidget(mSelectionList);
        mainLayout->addLayout(textureSelectionLayout);
        setLayout(mainLayout);
    }

    //****************************************************************************/
    QtAudioWidget::~QtAudioWidget(void)
    {
    }

    //****************************************************************************/
    void QtAudioWidget::addAudio(Source source, const QString& name, const QString& baseName)
    {
        QtAudioAndText* textureAndText = new QtAudioAndText(mIconDir, source, name, baseName, mTextureSize, this);
        QListWidgetItem* item = new QListWidgetItem();
        item->setSizeHint(mTextureSize); // Must be present, otherwise the widget is not shown
        mSelectionList->addItem(item);
        mSelectionList->setItemWidget(item, textureAndText);
        connect(mSelectionList, SIGNAL(itemClicked(QListWidgetItem*)), this, SLOT(handleSelected(QListWidgetItem*)));
        connect(mSelectionList, SIGNAL(itemDoubleClicked(QListWidgetItem*)), this, SLOT(handleDoubleClicked(QListWidgetItem*)));
        buildContextMenu();
    }

    //****************************************************************************/
    void QtAudioWidget::deleteAudio(const QString& name, bool nameIsFullName)
    {
        QtAudioAndText* textureAndText;
        QWidget* widget;
        int row;
        QList<QListWidgetItem*> list = mSelectionList->findItems(QString("*"), Qt::MatchWildcard);
        foreach (QListWidgetItem* item, list)
        {
            widget = mSelectionList->itemWidget(item);
            if (widget)
            {
                textureAndText = static_cast<QtAudioAndText*>(widget);
                if ((textureAndText->mName == name && nameIsFullName) ||
                    (textureAndText->mBaseName == name && !nameIsFullName))
                {
                    row = mSelectionList->row(item);
                    mSelectionList->removeItemWidget(item);
                    mSelectionList->takeItem(row);
                }
            }
        }
    }

    //****************************************************************************/
    bool QtAudioWidget::eventFilter(QObject* object, QEvent* event)
    {
        //QMessageBox::information(0, "test", "test"); // Test
        QMouseEvent* mouseEvent = (QMouseEvent*) event;
        switch ((int) event->type())
        {
            case QEvent::MouseButtonPress:
                mouseClickHandler(mouseEvent);
            break;

        }
        QObject::eventFilter(object, event);
        return false;
    }

    //****************************************************************************/
    void QtAudioWidget::mouseClickHandler(QMouseEvent* event)
    {
        switch ((int) event->button())
        {
            case Qt::RightButton:
            {
                handleSelected(mSelectionList->currentItem());
                if (mContextMenu)
                {
                    QPoint pos;
                    pos.setX(event->screenPos().x());
                    pos.setY(event->screenPos().y());
                    mContextMenu->popup(pos);
                }
            }
            break;
        }
    }

    //****************************************************************************/
    void QtAudioWidget::buildContextMenu(void)
    {
        if (!mContextMenu)
        {
            mSelectionList->viewport()->installEventFilter(this);
            mContextMenu = new QMenu(mSelectionList);
            connect(mContextMenu, SIGNAL(triggered(QAction*)), this, SLOT(contextMenuItemSelected(QAction*)));
            mContextMenu->addAction(new QAction(TOOL_AUDIOWIDGET_ACTION_PLAY, mSelectionList));
            mContextMenu->addAction(new QAction(TOOL_AUDIOWIDGET_ACTION_PAUSE, mSelectionList));
            mContextMenu->addAction(new QAction(TOOL_AUDIOWIDGET_ACTION_STOP, mSelectionList));
        }
    }

    //****************************************************************************/
    void QtAudioWidget::clearContent(void)
    {
        mSelectionList->clear();
    }

    //****************************************************************************/
    const QString& QtAudioWidget::getNameTexture(void)
    {
        return mNameTexture;
    }

    //****************************************************************************/
    const QString& QtAudioWidget::getBaseNameTexture(void)
    {
        return mBaseNameTexture;
    }

    //****************************************************************************/
    void QtAudioWidget::handleSelected(QListWidgetItem* item)
    {
        QWidget* widget = mSelectionList->itemWidget(item);
        if (widget)
        {
            QtAudioAndText* textureAndText = static_cast<QtAudioAndText*>(widget);

            // First stop the audio of the latest one
            if (mLastSelectedTextureAndText != textureAndText)
            {
                stopAudio(mLastSelectedTextureAndText);
                mLastSelectedTextureAndText = textureAndText;
            }
            emit selected(textureAndText->mName, textureAndText->mBaseName);
        }
    }

    //****************************************************************************/
    void QtAudioWidget::handleDoubleClicked(QListWidgetItem* item)
    {
        QWidget* widget = mSelectionList->itemWidget(item);
        if (widget)
        {
            QtAudioAndText* textureAndText = static_cast<QtAudioAndText*>(widget);
            playAudio(textureAndText->mSource, textureAndText->mName, textureAndText);
            mLastSelectedTextureAndText = textureAndText;
            emit doubleClicked(textureAndText->mName, textureAndText->mBaseName);
        }
    }

    //****************************************************************************/
    void QtAudioWidget::contextMenuItemSelected(QAction* action)
    {
        QListWidgetItem* item = mSelectionList->currentItem();
        if (item)
        {
            QtAudioAndText* textureAndText = static_cast<QtAudioAndText*>(mSelectionList->itemWidget(item));
            if (action->text() == TOOL_AUDIOWIDGET_ACTION_PLAY)
                playAudio(textureAndText->mSource, textureAndText->mName, textureAndText);
            else if (action->text() == TOOL_AUDIOWIDGET_ACTION_PAUSE)
                pauseAudio(textureAndText);
            else if (action->text() == TOOL_AUDIOWIDGET_ACTION_STOP)
                stopAudio(textureAndText);
        }
    }

    //****************************************************************************/
    void QtAudioWidget::handlePositionChanged(qint64 position)
    {
        qint64 size = mAudioPlayer->duration();
        if (position >= size)
        {
            QtAudioAndText* textureAndText = 0;
            QListWidgetItem* item = mSelectionList->currentItem();
            if (item)
                textureAndText = static_cast<QtAudioAndText*>(mSelectionList->itemWidget(item));

            stopAudio(textureAndText);
        }
    }

    //****************************************************************************/
    void QtAudioWidget::playAudio(Source source, QString name, QtAudioAndText* textureAndText)
    {
        if (name != mCurrentAudioPlaying)
            if (source == SOURCE_FILE)
            {
                mAudioPlayer->setMedia(QUrl::fromLocalFile(name));
                mCurrentAudioPlaying = name;
            }
        mAudioPlayer->setVolume(100);
        mAudioPlayer->play();

        if (textureAndText)
            textureAndText->setPlay();
    }

    //****************************************************************************/
    void QtAudioWidget::pauseAudio(QtAudioAndText* textureAndText)
    {
        if (textureAndText)
            textureAndText->setPause();

        mAudioPlayer->pause();
    }

    //****************************************************************************/
    void QtAudioWidget::stopAudio(QtAudioAndText* textureAndText)
    {
        if (textureAndText)
            textureAndText->setStop();

        mAudioPlayer->stop();
        mCurrentAudioPlaying = QString("");
    }

    //****************************************************************************/
    void QtAudioWidget::setTextureSize (QSize size)
    {
        mTextureSize = size;
    }

    //****************************************************************************/
    void QtAudioWidget::filter(const QString& pattern)
    {
        QtAudioAndText* textureAndText;
        QWidget* widget;
        QString name;
        QList<QListWidgetItem*> list = mSelectionList->findItems(QString("*"), Qt::MatchWildcard);
        foreach (QListWidgetItem* item, list)
        {
            widget = mSelectionList->itemWidget(item);
            if (widget)
            {
                textureAndText = static_cast<QtAudioAndText*>(widget);
                name = textureAndText->mBaseName;
                name = name.toLower();
                if (!name.contains(pattern))
                    item->setHidden(true);
            }
        }
    }

    //****************************************************************************/
    void QtAudioWidget::resetFilter(void)
    {
        QList<QListWidgetItem*> list = mSelectionList->findItems(QString("*"), Qt::MatchWildcard);
        foreach (QListWidgetItem* item, list)
            item->setHidden(false);
    }

}
