/****************************************************************************
**
** Copyright (C) 2014
**
** This file is generated by the Magus toolkit
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
** "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
** LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
** A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
** OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
** LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
** DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
** THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
** (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
** OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE."
**
****************************************************************************/

// Include
#include "tool_resourcewidget.h"
#include "tool_resourcewidget_assets.h"

namespace Magus
{
    //****************************************************************************/
    QtAssetsDockWidget::QtAssetsDockWidget(const QString& iconDir, const QString& title, QMainWindow* parent, Qt::WindowFlags flags) :
        QDockWidget (title, parent, flags),
        mParent(parent)
    {
        mIconDir = iconDir;
        mInnerMain = new QMainWindow();
        setWidget(mInnerMain);
        mTabWidget = new QTabWidget(mInnerMain);
        mInnerMain->setCentralWidget(mTabWidget);
        mTabWidget->show();
        QWidget* oldTitleBar = titleBarWidget();
        setTitleBarWidget(new QWidget());
        delete oldTitleBar;

        // Create audio selection widget
        mAudioSelection = new QtAudioWidget(mIconDir, this);
        mAudioSelection->setTextureSize(QSize(112, 120));

        // Create texture selection widget
        mTextureSelection = new QtDefaultTextureWidget(this);
        mTextureSelection->setTextureSize(QSize(112, 120));

        // -------------------------------------- Fill the assets widget --------------------------------------
        QIcon audioIcon(mIconDir + QString("audio.png"));
        QIcon materialIcon(mIconDir + QString("material.png"));
        QIcon meshIcon(mIconDir + QString("npc.png"));
        QIcon scriptIcon(mIconDir + QString("cog.png"));
        QIcon textureIcon(mIconDir + QString("texture.png"));
        addTab(mAudioSelection, audioIcon, QString("Audio"));
        addTab(new QWidget(this), materialIcon, QString("Materials")); // TODO: Update with widget
        addTab(new QWidget(this), meshIcon, QString("Meshes")); // TODO: Update with widget
        addTab(new QWidget(this), scriptIcon, QString("Scripts")); // TODO: Update with widget
        addTab(mTextureSelection, textureIcon, QString("Textures"));

        // Perform standard functions
        createActions();
        createMenus();
        createToolBars();

        connect(mTabWidget, SIGNAL(currentChanged(int)), this, SLOT(handleTabChanged(int)));
}

    //****************************************************************************/
    QtAssetsDockWidget::~QtAssetsDockWidget(void)
    {
    }

    //****************************************************************************/
    void QtAssetsDockWidget::addTab(QWidget* widget, const QIcon& icon, const QString name)
    {
        mTabWidget->addTab(widget, icon, name);
    }

    //****************************************************************************/
    void QtAssetsDockWidget::createActions(void)
    {
    }

    //****************************************************************************/
    void QtAssetsDockWidget::createMenus(void)
    {
    }

    //****************************************************************************/
    void QtAssetsDockWidget::createToolBars(void)
    {
    }

    //****************************************************************************/
    void QtAssetsDockWidget::addAsset(int toplevelId, int parentId, int resourceId, const QString& name, const QString& baseName)
    {
        switch (toplevelId)
        {
            case TOOL_SOURCES_LEVEL_X000_AUDIO:
            {
                // Add file(name) to mAudioSelection
                mAudioSelection->addAudio(SOURCE_FILE, name, baseName);
            }
            break;

            // TODO: Add Materials, Meshes, Scripts

            case TOOL_SOURCES_LEVEL_X000_TEXTURES:
            {
                // Add pixmap from file to mTextureSelection
                QPixmap pixmap(name);
                mTextureSelection->addTexture(pixmap, name, baseName);
            }
            break;
        }
    }

    //****************************************************************************/
    void QtAssetsDockWidget::selectTab(int toplevelId, int parentId, int resourceId, const QString& name, const QString& baseName)
    {
        mTabWidget->setCurrentIndex(toplevelId-1); // Assume that toplevelId follows pattern 1, 2, 3, 4, 5
    }

    //****************************************************************************/
    void QtAssetsDockWidget::deleteAsset(int toplevelId, const QString& name)
    {
        switch (toplevelId)
        {
            case TOOL_SOURCES_LEVEL_X000_AUDIO:
            {
                // Delete from mAudioSelection
                mAudioSelection->deleteAudio(name);
            }
            break;

            // TODO: Delete Materials, Meshes, Scripts

            case TOOL_SOURCES_LEVEL_X000_TEXTURES:
            {
                // Delete from mTextureSelection
                mTextureSelection->deleteTexture(name);
            }
            break;
        }
    }

    //****************************************************************************/
    void QtAssetsDockWidget::handleTabChanged(int index)
    {
        emit tabChanged(index + 1);
    }

}
