/****************************************************************************
**
** Copyright (C) 2015
**
** This file is generated by the Magus toolkit
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
** "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
** LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
** A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
** OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
** LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
** DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
** THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
** (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
** OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE."
**
****************************************************************************/

// Include
#include <QDir>
#include <QFileDialog>
#include "tool_filereader.h"
#include "generic_funtions.h"

namespace Magus
{
    //****************************************************************************/
    QtFileReader::QtFileReader(void)
    {
    }

    //****************************************************************************/
    QtFileReader::~QtFileReader(void)
    {
    }

    //****************************************************************************/
    const QVector<QPixmap>& QtFileReader::readTexturesRecursively(const QString& searchPath)
    {
        mPixmapVec.clear();

        // Get all texture files from all dirs/subdirs
        QDir dir(searchPath);
        dir.makeAbsolute();

        if (dir.exists())
        {
            Q_FOREACH(QFileInfo info, dir.entryInfoList(QDir::NoDotAndDotDot | QDir::System | QDir::Hidden  | QDir::AllDirs | QDir::Files, QDir::DirsFirst))
            {
                if (info.isDir())
                {
                    readTexturesRecursively(info.absoluteFilePath());
                }
                else
                {
                    QString fileName = info.absoluteFilePath();
                    if (isImageBasedOnExtension(fileName))
                    {
                        // It is an image
                        QPixmap texturePixmap = QPixmap(info.absoluteFilePath());
                        mPixmapVec.append(texturePixmap);
                        emit textureRead(texturePixmap, info.absoluteFilePath(), info.fileName());
                        emit fileRead(info.absoluteFilePath(), info.absolutePath());
                    }
                }
            }
        }

        return mPixmapVec;
    }

    //****************************************************************************/
    const QString& QtFileReader::readFileName(const QString& title, const QString& path)
    {
        mFileName = QFileDialog::getOpenFileName(0, title, path);
        if (!mFileName.isEmpty())
        {
            emit fileRead(mFileName, path);
        }

        return mFileName;
    }

}
