/****************************************************************************
**
** Copyright (C) 2014
**
** This file is generated by the Magus toolkit
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
** "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
** LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
** A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
** OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
** LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
** DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
** THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
** (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
** OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE."
**
****************************************************************************/

#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <QString>

//****************************************************************************/
static const int TB_ICON_AND_SPACING = 32;
static const QString NODE_TITLE_MATERIAL = QString("Material");
static const QString NODE_TITLE_TECHNIQUE = QString("Technique");
static const QString NODE_TITLE_PASS = QString("Pass");
static const QString NODE_TITLE_TEXTURE_UNIT = QString("Texture unit");
static const QString ASSET_ICON_CUBE_BOLD = QString("../common/icons/cube_bold.png");
static const QString ASSET_ICON_COLLAPSE = QString("../common/icons/collapse.png");
static const QString ASSET_ICON_EXPAND = QString("../common/icons/expand.png");
static const QString ICON_MATERIAL = QString("../common/icons/material.png");
static const QString ICON_MATERIAL_BOLD = QString("../common/icons/material_bold.png");
static const QString ICON_TECHNIQUE = QString("../common/icons/technique.png");
static const QString ICON_TECHNIQUE_BOLD = QString("../common/icons/technique_bold.png");
static const QString ICON_PASS = QString("../common/icons/pass.png");
static const QString ICON_PASS_BOLD = QString("../common/icons/pass_bold.png");
static const QString ICON_TEXTURE = QString("../common/icons/texture.png");
static const QString ICON_TEXTURE_BOLD = QString("../common/icons/texture_bold.png");
static const QString ICON_COG = QString("../common/icons/cog.png");
static const QString ICON_MINMAX = QString("../common/icons/minmax.png");
static const QString ICON_CLOSE = QString("../common/icons/close.png");

//****************************************************************************/
// Ports
static const QString PORT_TECHNIQUE_OUT = QString("technique (out)");
static const QString PORT_MATERIAL_IN = QString("material (in)");
static const QString PORT_PASS_OUT = QString("pass (out)");
static const QString PORT_TECHNIQUE_IN = QString("technique (in)");
static const QString PORT_TEXTURE_OUT = QString("texture (out)");
static const QString PORT_PASS_IN = QString("pass (in)");
static const unsigned int PORT_ID_MATERIAL = 10;
static const unsigned int PORT_ID_TECHNIQUE = 20;
static const unsigned int PORT_ID_PASS = 30;
static const unsigned int PORT_ID_TEXTURE_UNIT = 40;

//****************************************************************************/
// Assets
static const int ASSET_CONTAINER_MATERIAL_GENERAL = 10;
static const int ASSET_CONTAINER_TECHNIQUE_GENERAL = 20;
static const int ASSET_CONTAINER_PASS_GENERAL = 30;
static const int ASSET_CONTAINER_PASS_COLOR = 40;
static const int ASSET_CONTAINER_TEXTURE_UNIT_GENERAL = 5;

// Material
static const int ASSET_PROPERTY_MATERIAL_NAME = 10;
static const int ASSET_PROPERTY_MATERIAL_SCENE_BLENDING = 11;

// Pass
static const int ASSET_PROPERTY_PASS_DEPTH_CHECK = 21;
static const int ASSET_PROPERTY_PASS_DEPTH_WRITE = 22;
static const int ASSET_PROPERTY_PASS_LIGHTING = 23;
static const int ASSET_PROPERTY_PASS_AMBIENT = 24;
static const int ASSET_PROPERTY_PASS_DIFFUSE = 25;
static const int ASSET_PROPERTY_PASS_SPECULAR = 26;

// Texture unit
static const int ASSET_PROPERTY_TEXTURE_UNIT_TEXTURE = 31;

#endif
